### PR TITLE
[BAHIR-180] changes to improve eventual consistence

### PR DESCRIPTION
**Pull request by eskabetxe**

### CODE REVIEW

**Comment by eskabetxe** [comment]
@lresende cuando puedas

**Comment by eskabetxe** [comment]
@lresende downgrade versions.. i will create new PR for that

**Comment by eskabetxe** [comment]
@lresende could you check this

**Comment by lresende** [comment]
@eskabetxe there is still a pom change related to scala versions, other then that is looking good...

**Comment by eskabetxe** [comment]
@lresende its changed

**Pull request closed without merging**
