### PR TITLE
[BAHIR-179] fail silently with docker tests

### PR DESCRIPTION
**Pull request by eskabetxe**
change test to add integration test and avoid this kind test to be launch on local.

This PR must be merged after https://github.com/apache/bahir-flink/pull/33

### CODE REVIEW

**Comment by eskabetxe** [comment]
@lresende, @rmetzger

**Comment by eskabetxe** [comment]
@lresende

**Comment by lresende** [comment]
@eskabetxe Please rebase your PR. Also, I see a few changes on different projects other than the flume tests from bahir-114 (including disabling tests that are working on current master) that we are trying to address. If these are additional enhancements, please create different prs and smaller ones.

**Comment by lresende** [comment]
BTW, I have disabled the failing docker tests in master after applying your last pr #33

**Comment by eskabetxe** [comment]
hi @lresende,
the changes are because i change:
- the tests with docker images, this affect the projects of flume and kudu
- upgrade junit to version 5.3.1
- the test disabled, is not working on master, because its ignored because actual parent pom have this
            <includes>	           
              <include>**/Test*.java</include>	
              <include>**/*Test.java</include>	
              <include>**/*TestCase.java</include>	
              <include>**/*Suite.java</include>	
            </includes>
and the test class is named ActiveMQConnectorITCase and its not working, if you launch the test on local you will see that fail..

**Comment by eskabetxe** [comment]
@lresende i change the commits to be one by project and be more easy to see the changes
all the changes are related by the upgrade of junit version, but if you still prefer a distinct PR for every change i could do it.

**Comment by eskabetxe** [comment]
@lresende any change to merge this

**Comment by lresende** [comment]
@eskabetxe if you update to latest master and try to rebase this, do you get any conflicts ? 
This is what I am getting :
```
First, rewinding head to replay your work on top of it...
Applying: BAHIR-114: update flume to 1.8 and add some tests
Using index info to reconstruct a base tree...
M	.travis.yml
M	flink-connector-flume/README.md
M	flink-connector-flume/pom.xml
M	flink-connector-flume/src/main/java/org/apache/flink/streaming/connectors/flume/FlumeSink.java
M	pom.xml
Falling back to patching base and 3-way merge...
Auto-merging pom.xml
CONFLICT (content): Merge conflict in pom.xml
Auto-merging flink-connector-flume/src/test/java/org/apache/flink/streaming/connectors/flume/FlumeSinkTest.java
CONFLICT (add/add): Merge conflict in flink-connector-flume/src/test/java/org/apache/flink/streaming/connectors/flume/FlumeSinkTest.java
Auto-merging .travis.yml
CONFLICT (content): Merge conflict in .travis.yml
error: Failed to merge in the changes.
Patch failed at 0001 BAHIR-114: update flume to 1.8 and add some tests
Use 'git am --show-current-patch' to see the failed patch

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
```

**Comment by eskabetxe** [comment]
@lresende updated with master..

**Comment by eskabetxe** [comment]
@lresende could you merge this

**Pull request closed without merging**
