### PR TITLE
1. update flink version to 1.11.3

### PR DESCRIPTION
**Pull request by cheegoday**
2. fix netty connector unit test

### CODE REVIEW

**Comment by cheegoday** [comment]
1. unit test will go wrong without dependencies below, so i add those dependencies to pom.xml of flink-netty-connector
```xml
    <dependency>
      <groupId>org.apache.flink</groupId>
      <artifactId>flink-table-planner-blink_${scala.binary.version}</artifactId>
      <version>${flink.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.flink</groupId>
      <artifactId>flink-clients_${scala.binary.version}</artifactId>
      <version>${flink.version}</version>
      <scope>test</scope>
    </dependency>
```

2. update flink version to 1.11.3

**Comment by cheegoday** [comment]
@lresende hi, please review my PR

**Comment by eskabetxe** [comment]
Thanks @cheegoday  for the contribution :)

Could you change travis file to use the same flink version

**Comment by cheegoday** [comment]
> Thanks @cheegoday for the contribution :)
> 
> Could you change travis file to use the same flink version

**Comment by eskabetxe** [comment]
@cheegoday merged, thanks

**Pull request merged**
