### PR TITLE
[BAHIR-114] update flume to 1.8 and add some tests

### PR DESCRIPTION
**Pull request by eskabetxe**
update flume to 1.8 
added some tests

### CODE REVIEW

**Comment by eskabetxe** [comment]
@lresende, @rmetzger could you check this

**Comment by lresende** [comment]
@eskabetxe Could you please rebase this? I rebased locally and the tests started failing with
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Picked up _JAVA_OPTIONS: -Dfile.encoding=UTF-8
Running org.apache.flink.streaming.connectors.flume.FlumeSinkTest
19:50:38,818 WARN  org.apache.flink.runtime.dispatcher.DispatcherRestEndpoint    - Upload directory /var/folders/6w/8vng5v895fd8kmf8q8sk_yzw0000gn/T/flink-web-upload does not exist, or has been deleted externally. Previously uploaded files are no longer available.
19:50:39,031 WARN  org.apache.flink.runtime.webmonitor.WebMonitorUtils           - Log file environment variable 'log.file' is not set.
19:50:39,031 WARN  org.apache.flink.runtime.webmonitor.WebMonitorUtils           - JobManager log files are unavailable in the web dashboard. Log file location not found in environment variable 'log.file' or configuration key 'Key: 'web.log.path' , default: null (deprecated keys: [jobmanager.web.log.path])'.
19:50:39,485 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Invalid value for batchSize: 0; Using default value.
19:50:39,485 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Invalid value for batchSize: 0; Using default value.
19:50:39,485 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Invalid value for batchSize: 0; Using default value.
19:50:39,485 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Invalid value for batchSize: 0; Using default value.
19:50:39,485 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Invalid value for batchSize: 0; Using default value.
19:50:39,485 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Invalid value for batchSize: 0; Using default value.
19:50:39,485 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Invalid value for batchSize: 0; Using default value.
19:50:39,485 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Invalid value for batchSize: 0; Using default value.
19:50:39,495 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Using default maxIOWorkers
19:50:39,495 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Using default maxIOWorkers
19:50:39,495 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Using default maxIOWorkers
19:50:39,495 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Using default maxIOWorkers
19:50:39,495 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Using default maxIOWorkers
19:50:39,495 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Using default maxIOWorkers
19:50:39,495 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Using default maxIOWorkers
19:50:39,495 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Using default maxIOWorkers
19:50:39,501 WARN  org.apache.flink.runtime.filecache.FileCache                  - improper use of releaseJob() without a matching number of createTmpFiles() calls for jobId 50b0500d2ae09ebf50a0085792436fdf
19:51:00,623 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Invalid value for batchSize: 0; Using default value.
19:51:00,623 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Invalid value for batchSize: 0; Using default value.
19:51:00,624 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Using default maxIOWorkers
19:51:00,624 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Invalid value for batchSize: 0; Using default value.
19:51:00,623 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Invalid value for batchSize: 0; Using default value.
19:51:00,623 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Invalid value for batchSize: 0; Using default value.
19:51:00,623 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Invalid value for batchSize: 0; Using default value.
19:51:00,625 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Using default maxIOWorkers
19:51:00,623 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Invalid value for batchSize: 0; Using default value.
19:51:00,623 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Invalid value for batchSize: 0; Using default value.
19:51:00,626 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Using default maxIOWorkers
19:51:00,625 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Using default maxIOWorkers
19:51:00,625 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Using default maxIOWorkers
19:51:00,624 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Using default maxIOWorkers
19:51:00,624 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Using default maxIOWorkers
19:51:00,626 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Using default maxIOWorkers
19:51:21,658 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Invalid value for batchSize: 0; Using default value.
19:51:21,658 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Invalid value for batchSize: 0; Using default value.
19:51:21,658 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Invalid value for batchSize: 0; Using default value.
19:51:21,658 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Invalid value for batchSize: 0; Using default value.
19:51:21,658 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Invalid value for batchSize: 0; Using default value.
19:51:21,660 WARN  org.apache.flume.api.NettyAvroRpcClient                       - Using default maxIOWorkers
```

**Comment by eskabetxe** [comment]
@lresende done.. 
you have to start docker image so the test run perfect

**Comment by lresende** [comment]
Thanks @eskabetxe. 
Could this be automated, or fail silently if running locally and be automated on travis.ci?

**Comment by eskabetxe** [comment]
i think i could rename de tests to DockerTest and exclude them in pom configuration..
could be an option?

**Comment by eskabetxe** [comment]
@lresende could you merge this i will create a new issue to see how to fail silently the tests that need docker to be running

**Comment by lresende** [comment]
With the current PR, what's the developer experience when he clones the repository and tries to build?

**Comment by eskabetxe** [comment]
the same.. it could build if skip the test..

if you merge this, i can create a new PR with the solution (BAHIR-179)

**Comment by eskabetxe** [comment]
@lresende, @rmetzger

**Comment by eskabetxe** [comment]
@lresende

**Pull request closed without merging**
