### PR TITLE
add zincrby command

### PR DESCRIPTION
**Pull request by Git-Charles**
add zincrby command

### CODE REVIEW

**Comment by eskabetxe** [comment]
Thank you for the contribution :)
Can you add some testing for this command?

**Comment by Git-Charles** [comment]
I'd love to.


lei_charles@163.com
 
From: Joao Boto
Date: 2020-07-14 05:33
To: apache/bahir-flink
CC: lei_charles; Author
Subject: Re: [apache/bahir-flink] add zincrby command (#86)
Thank you for the contribution :)
Can you add some testing for this command?

**Comment by Git-Charles** [comment]
add zincrby command test case

**Comment by eskabetxe** [comment]
@Git-Charles can you squash all commits into one

**Pull request merged**
