### PR TITLE
[BAHIR-210] upgrade flink to 1.8.1

### PR DESCRIPTION
**Pull request by eskabetxe**
upgrade flink to 1.8.1

### CODE REVIEW

**Comment by eskabetxe** [comment]
@lresende could you check

**Comment by lresende** [comment]
@eskabetxe could you check the build failures, it might be related to Travis load, but it usually passes so it might also be a side effect of the upgrade?

**Comment by eskabetxe** [comment]
this is the error 
"The job exceeded the maximum log length, and has been terminated."

i have pending to check all the warnings..
i will see if there are some easy error to solve

**Comment by eskabetxe** [comment]
@lresende i added a -quiet option to mvn command.. 
that way only logs the errors...

**Pull request merged**
