### PR TITLE
[BAHIR-308] Bump flink to 1.17

### PR DESCRIPTION
**Pull request by eskabetxe**
Failing tests:
**influxdb2** 
@1p4pk could you help?
falling test: InfluxDBSinkIntegrationTestCase.testSinkDataToInfluxDB

**kudu**
@collabH could you help here..
on kudu connector, in the KuduDynamicTableSource
```
   @Override
    public void applyProjection(int[][] projectedFields) {
        // parser projectFields
        this.physicalSchema = TableSchemaUtils.projectSchema(this.physicalSchema, projectedFields);
        this.projectedFields = physicalSchema.getFieldNames();
    }
```
the TableSchemaUtils.projectSchema no more exists on 1.15..

**pinot** 
@mschroederi could you help?

### CODE REVIEW

**Comment by eskabetxe** [comment]
@collabH could you help here..
on kudu, in the KuduDynamicTableSource
    @Override
    public void applyProjection(int[][] projectedFields) {
        // parser projectFields
        this.physicalSchema = TableSchemaUtils.projectSchema(this.physicalSchema, projectedFields);
        this.projectedFields = physicalSchema.getFieldNames();
    }

the TableSchemaUtils.projectSchema no more exists on 1.15..
could you check please

**Comment by collabH** [comment]
> Failing tests: **influxdb2** @1p4pk could you help? falling test: InfluxDBSinkIntegrationTestCase.testSinkDataToInfluxDB
> 
> **kudu** @collabH could you help here.. on kudu connector, in the KuduDynamicTableSource
> 
> ```
>    @Override
>     public void applyProjection(int[][] projectedFields) {
>         // parser projectFields
>         this.physicalSchema = TableSchemaUtils.projectSchema(this.physicalSchema, projectedFields);
>         this.projectedFields = physicalSchema.getFieldNames();
>     }
> ```
> 
> the TableSchemaUtils.projectSchema no more exists on 1.15..
> 
> **pinot** @mschroederi could you help?

@eskabetxe Hi,I can't submit code to this PR without permission

**Comment by eskabetxe** [comment]
@collabH you can create a PR to this branch..

**Comment by collabH** [comment]
> @collabH you can create a PR to this branch..

Ok，link to [fix kudu](https://github.com/apache/bahir-flink/pull/152#issue-1307446879)

**Comment by 1p4pk** [comment]
Hi @eskabetxe,

I will take a look this weekend!

**Comment by eskabetxe** [comment]
@1p4pk could you see anything?

**Comment by 1p4pk** [comment]
Hi  @eskabetxe,

sorry for the delay, but yes I spent some time on it and found several things. Also talked to Arvid Heise about it. In general, your version bump leads to the introduction of Soruce/Sink v2 but this connector was built using v1. There are adapters that should guarantee the same behaviour, unfortunately I think is slightly does not.

However, I found to things:
in the InfluxDBWriter::write, should actually look like that:
``` java
public void write(final IN in, final Context context) throws IOException {
        if (this.elements.size() == this.bufferSize) {
            LOG.debug("Buffer size reached preparing to write the elements.");
            this.writeCurrentElements();
            this.elements.clear();
        }

        LOG.trace("Adding elements to buffer. Buffer size: {}", this.elements.size());
        this.elements.add(this.schemaSerializer.serialize(in, context));
        if (context.timestamp() != null) {
            this.lastTimestamp = Math.max(this.lastTimestamp, context.timestamp());
        }
    }
```

In the InfluxDBSinkIntegrationTestCase::testSinkDataToInfluxDB, the query should look like that:
``` java
env.addSource(new FiniteTestSource<>(SOURCE_DATA), BasicTypeInfo.LONG_TYPE_INFO)
        .assignTimestampsAndWatermarks(WatermarkStrategy.<Long>noWatermarks()
            .withTimestampAssigner((event, timestamp) -> System.nanoTime()))
        .sinkTo(influxDBSink);
```

Of course also add the correct dependencies.
Besides, I still have the problem that the commits are not generated, which is due to a slight  behviour change by the adapter. Unfortunately, I do not have so much time atm, as I am finishing my master thesis. I can do a drill down a bit later, but not atm. Hope that helped at least a little bit.

**Comment by eskabetxe** [comment]
Hi @1p4pk ,
Im checking this again, as 1.16 as been release..
I create a sink2 version of the sink but Im getting stuck on same method, queryCheckpoints is always returning 0

I don't know if you have some time now to check

**Comment by zpf7879** [comment]
Hi, this is a great effort to catch up the Flink update. Wondering when this can be merged into the main? @1p4pk

**Comment by eskabetxe** [comment]
Merged

**Pull request merged**
