### PR TITLE
Improved integration test cases for flink-library-siddhi

### PR DESCRIPTION
**Pull request by chermenin**
This PR is intended to fix periodically unstable test method `testUnboundedPojoStreamSimplePatternMatch` in the integration test cases for `flink-library-siddhi`.

### CODE REVIEW

**Comment by haoch** [comment]
LGTM,  the fix helps improve test case stability.

**Comment by haoch** [comment]
@rmetzger could you please help review the fix?

**Comment by chermenin** [comment]
@haoch I saw that you added my commits to your other pull request. Is it needed to close this one or it can just stay here?

**Comment by rmetzger** [comment]
Thanks a lot for improving the tests stability.
I'll review the PR and the merge it :)

**Comment by rmetzger** [comment]
I've filed https://issues.apache.org/jira/browse/BAHIR-156 to have a JIRA id for this issue.

I'll now merge the PR

**Comment by haoch** [comment]
@chermenin please just keep this one to ensure your own contribution merged firstly.

**Pull request closed without merging**
