### PR TITLE
add support "upsert part of columns of a kudu table"

### PR DESCRIPTION
**Pull request by lintingbin2009**
Sometimes we don't want to upsert all columns of a kudu table. So we need support the function that upsert part of columns of a kudu table.

### CODE REVIEW

**Comment by eskabetxe** [comment]
Hi @lintingbin2009, thanks for the PR

could you add some test to this case?

**Comment by lintingbin2009** [comment]
Hi @eskabetxe, I have added some test case to this PR.

**Comment by eskabetxe** [comment]
@lresende LGTM

**Comment by lintingbin2009** [comment]
Hi @lresende, When to build a new jar package for kudu connector?

**Comment by xiaoxi0xiaoxi** [comment]
@lintingbin2009 Hopefully Flink SQL can also support it.

**Pull request merged**
