### PR TITLE
[hotfix] Fix flume sink and utils test

### PR DESCRIPTION
**Pull request by raminqaf**
Currently, the two tests of the module `flink-conector-flume` are failing. Down here you can see the logs printed after running `mvn test -pl flink-connector-flume` command in my terminal. It seems that `testcontainers` is failing to pull the flume container. To fix the issue I have just updated the `testcontainers` dependency to the newest version (1.15.3).
```console
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.flink.streaming.connectors.flume.FlumeUtilsTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.766 s <<< FAILURE! - in org.apache.flink.streaming.connectors.flume.FlumeUtilsTest
[ERROR] testGetRpcClient  Time elapsed: 0.647 s  <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=eskabetxe/flume:latest, imagePullPolicy=DefaultPullPolicy())
Caused by: com.github.dockerjava.api.exception.NotFoundException: 
{"message":"No such image: testcontainersofficial/ryuk:0.3.0"}


[ERROR] testDestroy  Time elapsed: 0.075 s  <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=eskabetxe/flume:latest, imagePullPolicy=DefaultPullPolicy())
Caused by: com.github.dockerjava.api.exception.NotFoundException: 
{"message":"No such image: testcontainersofficial/ryuk:0.3.0"}


[INFO] Running org.apache.flink.streaming.connectors.flume.FlumeSinkTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.067 s <<< FAILURE! - in org.apache.flink.streaming.connectors.flume.FlumeSinkTest
[ERROR] testSink  Time elapsed: 0.067 s  <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=eskabetxe/flume:latest, imagePullPolicy=DefaultPullPolicy())
Caused by: com.github.dockerjava.api.exception.NotFoundException: 
{"message":"No such image: testcontainersofficial/ryuk:0.3.0"}


[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   FlumeSinkTest>FlumeServerTest.start:41 » ContainerLaunch Container startup fai...
[ERROR]   FlumeUtilsTest>FlumeServerTest.start:41 » ContainerLaunch Container startup fa...
[ERROR]   FlumeUtilsTest>FlumeServerTest.start:41 » ContainerLaunch Container startup fa...
[INFO] 
[ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.352 s
[INFO] Finished at: 2021-05-12T13:34:52+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project flink-connector-flume_2.11: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/ramin/Developer/bahir-flink/flink-connector-flume/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

### CODE REVIEW

**Review by rmetzger — APPROVED** [review]
I think a `[hotfix]` prefixed commit would be the right formatting for such a quick fix.

**Comment by rmetzger** [comment]
I adjusted the commit message while merging!

**Comment by raminqaf** [comment]
@rmetzger I am a bit confused. Is this PR now merged or closed?

**Comment by rmetzger** [comment]
It's merged to master, and I closed the PR.

**Pull request closed without merging**
