### PR TITLE
flink-conector-kudu supports flink1.11

### PR DESCRIPTION
**Pull request by TheEros**

### CODE REVIEW

**Comment by lresende** [comment]
Should we actually move to `Flink 1.11.1` ?

**Comment by eskabetxe** [comment]
Yes, there are critical fixes on TableSql Api

**Comment by lsasta** [comment]
hi
Can you change the version? Since the previous flink version of 1.7.0 was ' 1.1-snapshot ', now flink-1.11 is the same ' 1.1-snapshot '. The changes corresponding to 1.11 cannot now be obtained from the Maven repository.

**Comment by gyfora** [comment]
Hi! @TheEros can you please put all the changes in a single commit and rebase on master?

**Comment by gyfora** [comment]
This PR does not fix a lot of test failures and ignores other submodules, I am working on a change to upgrade all connectors to 1.11 while maintaining functionality.

I suggest we close this PR

**Comment by eskabetxe** [comment]
closed by https://github.com/apache/bahir-flink/pull/99

**Pull request closed without merging**
