### PR TITLE
[BAHIR-264] Dedup dependencies in flink-connector-redis

### PR DESCRIPTION
**Pull request by YikSanChan**
As titled.

### CODE REVIEW

**Comment by eskabetxe** [comment]
Thanks @YikSanChan for your contribution

I saw a lot of 2.11 on dependencies could you change that to

for example this
            <artifactId>flink-table-api-java-bridge_2.11</artifactId>
with this
            <artifactId>flink-table-api-java-bridge_${scala.binary.version}</artifactId>

**Comment by YikSanChan** [comment]
@eskabetxe done

**Comment by eskabetxe** [comment]
@YikSanChan  thanks, waiting for tests

**Comment by eskabetxe** [comment]
@YikSanChan merged, thanks

**Comment by YikSanChan** [comment]
@eskabetxe thanks

**Pull request merged**
