### PR TITLE
[BAHIR-283] prevent each element from infludb2 sink buffer from being dropped

### PR DESCRIPTION
**Pull request by dquig**
See JIRA issue: https://issues.apache.org/jira/browse/BAHIR-283

### CODE REVIEW

**Comment by eskabetxe** [comment]
@rmetzger could you check?

**Comment by eskabetxe** [comment]
Thanks for your contribution @dquig

**Comment by daniel-packard** [comment]
Hi @eskabetxe - 

Is there a release schedule for the next version of this sink?

currently using this version, which doesn't have the fix:
```
<dependency>
	<groupId>org.apache.bahir</groupId>
	<artifactId>flink-connector-influxdb2_2.12</artifactId>
	<version>1.2-SNAPSHOT</version>
	<scope>compile</scope>
</dependency>
```

**Comment by eskabetxe** [comment]
Hi @daniel-packard,
I update the Snapshots, the fix should be available.

We are finishing the migration to Flink 1.17 when finished we should have a new release.

**Pull request merged**
