### PR TITLE
[BAHIR-243] Change KuduTestHarness with TestContainers

### PR DESCRIPTION
**Pull request by eskabetxe**
KuduTestHarness not work on all distributions of linux as it must be released by kudu team an artifact for that distribution.

This change the use of KuduTestHarness with TestContainers that allow to have a docker container for testing

[related to this](https://issues.apache.org/jira/projects/KUDU/issues/KUDU-3174)

### CODE REVIEW

**Comment by eskabetxe** [comment]
@gyfora, @lresende  could you check

**Comment by gyfora** [comment]
I will try to check this today or tomorrow!

**Comment by gyfora** [comment]
Have you tested this on OSX? I am trying to run it locally but I get all kinds of failures and everything seems to be incredibly slow.

**Comment by eskabetxe** [comment]
no, only tested on different distributions of linux.
first time will be "slow" as it have to download docker image.

**Comment by thebalu** [comment]
Hi, I've also tried to run the tests locally on OSX, and the tests involving the use of TestContainers all break for me too. They seem to timeout. I've pulled the kudu docker container as well.

**Comment by eskabetxe** [comment]
@bsideup could you help here
TestContainers is not working in OSX, is there any limitation?

**Comment by bsideup** [comment]
@eskabetxe 2 out of 3 Testcontainers maintainers are working on the project on Mac OS X, so I am surprised to hear that it is not working ;)

What exactly is not working? Any logs?

**Comment by eskabetxe** [comment]
@bsideup good to know :)
@gyfora, @thebalu could you share the logs or tell what doesn't work?

**Comment by thebalu** [comment]
It is a mix of various errors, it seems that the containers can't be reached, or they time out. For example, 

```
java.io.IOException: Error while sending value. 
 Row error for primary key=[-128, 0, 0, 3], tablet=null, server=null, status=Timed out: cannot complete before timeout: Batch{operations=168, tablet="36fbbdca761f4a5fa7644cbef9b7a607" [0x00000002, 0x00000003), ignoredErrors=[], rpc=KuduRpc(method=Write, tablet=36fbbdca761f4a5fa7644cbef9b7a607, attempt=3, TimeoutTracker(timeout=30000, elapsed=30020), Trace Summary(20079 ms): Sent(3), Received(2), Delayed(2), MasterRefresh(0), AuthRefresh(0), Truncated: false
 Sent: (c5150b18912548e7a7b57a009aa5a1e8, [ Write, 3 ])
 Received: (c5150b18912548e7a7b57a009aa5a1e8, [ NETWORK_ERROR, 2 ])
 Delayed: (UNKNOWN, [ Write, 2 ]))}
```

Is there any setup we need to do before running the tests?

**Comment by bsideup** [comment]
@thebalu no setup is required, installed Docker for Mac is the only pre-requisite.

The errors seems to be product related, nothing about Testcontainers. Could you please try running some simple TC-based test (e.g. just Redis or something), maybe there is an issue with your test setup and not the library itself?
Also, we run a few checks at startup that won't let you continue if there is a problem. Since the logs you shared seem to be after the setup phase, I guess the checks passed, which usually means that all good on the lib side.

**Comment by bsideup** [comment]
I am not familiar with Kudu, but this line looks suspicious:

> [ NETWORK_ERROR, 2 ]), (master-localhost:32799,

what is `master-localhost`? Make sure that you're using `Container#getHost()` for the host when you access the container from the machine that runs the tests.

**Comment by gyfora** [comment]
I get the same errors as @thebalu , I am not saying thet TestContainers in general don't work, just that these tests consistently fail for me as well

**Comment by bsideup** [comment]
Does it work if the container is started via `docker run ...` (make sure to use random ports)?

**Comment by thebalu** [comment]
I've been looking into it a bit, but I am not too familiar with Docker / TestContainers.

So the `localhost:32799` (port is always random) comes from this line:
`masterAddress = HostAndPort.fromParts(master.getContainerIpAddress(), master.getMappedPort(KUDU_MASTER_PORT)).toString();`

`master.getHost()` returns localhost as well.

The containers get successfully created in the `beforeClass`, I am able to see master logs inside the container (but not in the tserver containers).
It seems that at some point after a request is received (I can see the CreateTableRequest in the master logs), there is a communication error between the master and tservers, and all containers crash/terminate. I wasn't able to recover their full logs afterwards, but these lines appear not long before the crash in the master container:
```
I0827 15:29:30.977533   134 catalog_manager.cc:4136] T 9af663be017b44d188234a7cb11d7d32 P 534ed6b36ec04fb5b19a012b196dd36b reported cstate change: term changed from 0 to 1, leader changed from <none> to 534ed6b36ec04fb5b19a012b196dd36b (192.168.80.5). New cstate: current_term: 1 leader_uuid: "534ed6b36ec04fb5b19a012b196dd36b" committed_config { opid_index: -1 OBSOLETE_local: true peers { permanent_uuid: "534ed6b36ec04fb5b19a012b196dd36b" member_type: VOTER last_known_addr { host: "192.168.80.5" port: 7050 } health_report { overall_health: HEALTHY } } }
I0827 15:29:30.981220   134 catalog_manager.cc:4136] T 38d2fb973558459e9150354ceee68d72 P df98f3e17885477595190ba2dab55530 reported cstate change: term changed from 0 to 1, leader changed from <none> to df98f3e17885477595190ba2dab55530 (192.168.80.3). New cstate: current_term: 1 leader_uuid: "df98f3e17885477595190ba2dab55530" committed_config { opid_index: -1 OBSOLETE_local: true peers { permanent_uuid: "df98f3e17885477595190ba2dab55530" member_type: VOTER last_known_addr { host: "192.168.80.3" port: 7050 } health_report { overall_health: HEALTHY } } }
W0827 15:30:01.096755   117 connection.cc:655] server connection from 192.168.80.5:44398 recv error: Network error: failed to read from TLS socket (remote: 192.168.80.5:44398): Connection reset by peer (error 104)
W0827 15:30:01.097028   114 connection.cc:655] client connection to 192.168.80.5:7050 recv error: Network error: failed to read from TLS socket (remote: 192.168.80.5:7050): Connection reset by peer (error 104)
W0827 15:30:01.342813   115 connection.cc:655] server connection from 192.168.80.4:48140 recv error: Network error: failed to read from TLS socket (remote: 192.168.80.4:48140): Connection reset by peer (error 104)
```

@bsideup Do you mean starting the kudu containers manually with docker run, and hardcoding their ports in the test?

**Comment by eskabetxe** [comment]
@bsideup could be the use of network aliases that could cause some problem in OSX? 

I added the web interface so we can see more easy if is running well the cluster..
@thebalu could you test with last changes..

if you set a breakpoint on line 104 of KuduTestBase you should be able to enter webui and see if cluster is running well
in Tablet Servers menu you should see something like this
image

**Comment by HsbcJone** [comment]
Hi  when the flink-connector-kudu  can suppport Flink1.11

**Pull request closed without merging**
