### PR TITLE
[BAHIR-129] Upgrade Flink version to 1.3.0

### PR DESCRIPTION
**Pull request by yew1eb**
Upgrade Flink version from 1.2.0 to 1.3.0.

## Brief change log
- travis build, remove oraclejdk7(  [Travis: oraclejdk7 is not available anymore](https://github.com/travis-ci/travis-ci/issues/7884#issuecomment-308451879)) and add openjdk8.
- travis build, define unique CACHE_NAME in case the auto-generated ones are not unique.
- upgrade flink version, fix It brings the problems.

## Verifying this change
- Travis build has passed。

### CODE REVIEW

**Comment by yew1eb** [comment]
CC @rmetzger

**Comment by lresende** [comment]
LGTM

**Comment by yew1eb** [comment]
Hi, @lresende Thanks for your attention to the PR.
 
Maybe we should add a new release for flink 1.3.0 ?

Best,
Hai

**Comment by lresende** [comment]
@yew1eb Could you please start a discussion on the dev list.

**Pull request closed without merging**
